FROM alpine as build
# install build tools
RUN apk add go git
RUN go env -w GOPROXY=direct
# cache dependencies
ADD go.mod go.sum ./
RUN go mod download 
# build
ADD . .
ENV GO111MODULE=on
RUN GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o /main /main.go
# copy artifacts to a clean image
FROM alpine
COPY --from=build /main /main